; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
build_type = debug
monitor_filters = esp32_exception_decoder
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
lib_deps = 
	robtillaart/INA226@^0.6.4
	adafruit/RTClib@^2.1.4
	s00500/ESPUI@^2.2.4
	terrorsl/sMQTTBroker@^0.1.8
	cyijun/ESP32MQTTClient@^1.1.1
  	https://github.com/PowerStat/LTC6802.git
build_flags = -std=gnu++17
build_unflags = -std=gnu++11
